// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.3
// source: secretcard.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SecretCard struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId     string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name       string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Url        string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	Login      string                 `protobuf:"bytes,5,opt,name=login,proto3" json:"login,omitempty"`
	Password   string                 `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	Text       string                 `protobuf:"bytes,7,opt,name=text,proto3" json:"text,omitempty"`
	UpdateTime *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
}

func (x *SecretCard) Reset() {
	*x = SecretCard{}
	if protoimpl.UnsafeEnabled {
		mi := &file_secretcard_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SecretCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretCard) ProtoMessage() {}

func (x *SecretCard) ProtoReflect() protoreflect.Message {
	mi := &file_secretcard_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretCard.ProtoReflect.Descriptor instead.
func (*SecretCard) Descriptor() ([]byte, []int) {
	return file_secretcard_proto_rawDescGZIP(), []int{0}
}

func (x *SecretCard) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SecretCard) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SecretCard) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SecretCard) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *SecretCard) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *SecretCard) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *SecretCard) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SecretCard) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

type FileSecretCard struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CardId string `protobuf:"bytes,2,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	File   []byte `protobuf:"bytes,3,opt,name=file,proto3" json:"file,omitempty"`
}

func (x *FileSecretCard) Reset() {
	*x = FileSecretCard{}
	if protoimpl.UnsafeEnabled {
		mi := &file_secretcard_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileSecretCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileSecretCard) ProtoMessage() {}

func (x *FileSecretCard) ProtoReflect() protoreflect.Message {
	mi := &file_secretcard_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileSecretCard.ProtoReflect.Descriptor instead.
func (*FileSecretCard) Descriptor() ([]byte, []int) {
	return file_secretcard_proto_rawDescGZIP(), []int{1}
}

func (x *FileSecretCard) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FileSecretCard) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

func (x *FileSecretCard) GetFile() []byte {
	if x != nil {
		return x.File
	}
	return nil
}

type MetaSecretCard struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CardId string `protobuf:"bytes,2,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	Key    string `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Value  string `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *MetaSecretCard) Reset() {
	*x = MetaSecretCard{}
	if protoimpl.UnsafeEnabled {
		mi := &file_secretcard_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetaSecretCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaSecretCard) ProtoMessage() {}

func (x *MetaSecretCard) ProtoReflect() protoreflect.Message {
	mi := &file_secretcard_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaSecretCard.ProtoReflect.Descriptor instead.
func (*MetaSecretCard) Descriptor() ([]byte, []int) {
	return file_secretcard_proto_rawDescGZIP(), []int{2}
}

func (x *MetaSecretCard) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MetaSecretCard) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

func (x *MetaSecretCard) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *MetaSecretCard) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_secretcard_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_secretcard_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_secretcard_proto_rawDescGZIP(), []int{3}
}

type CreateSecretCardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId   string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Url      string `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Login    string `protobuf:"bytes,4,opt,name=login,proto3" json:"login,omitempty"`
	Password string `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	Text     string `protobuf:"bytes,6,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *CreateSecretCardRequest) Reset() {
	*x = CreateSecretCardRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_secretcard_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSecretCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSecretCardRequest) ProtoMessage() {}

func (x *CreateSecretCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_secretcard_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSecretCardRequest.ProtoReflect.Descriptor instead.
func (*CreateSecretCardRequest) Descriptor() ([]byte, []int) {
	return file_secretcard_proto_rawDescGZIP(), []int{4}
}

func (x *CreateSecretCardRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateSecretCardRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSecretCardRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CreateSecretCardRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *CreateSecretCardRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateSecretCardRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type ReadSecretCardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ReadSecretCardRequest) Reset() {
	*x = ReadSecretCardRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_secretcard_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadSecretCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadSecretCardRequest) ProtoMessage() {}

func (x *ReadSecretCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_secretcard_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadSecretCardRequest.ProtoReflect.Descriptor instead.
func (*ReadSecretCardRequest) Descriptor() ([]byte, []int) {
	return file_secretcard_proto_rawDescGZIP(), []int{5}
}

func (x *ReadSecretCardRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateSecretCardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId   string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name     string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Url      string `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	Login    string `protobuf:"bytes,5,opt,name=login,proto3" json:"login,omitempty"`
	Password string `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	Text     string `protobuf:"bytes,7,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *UpdateSecretCardRequest) Reset() {
	*x = UpdateSecretCardRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_secretcard_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateSecretCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSecretCardRequest) ProtoMessage() {}

func (x *UpdateSecretCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_secretcard_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSecretCardRequest.ProtoReflect.Descriptor instead.
func (*UpdateSecretCardRequest) Descriptor() ([]byte, []int) {
	return file_secretcard_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateSecretCardRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateSecretCardRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateSecretCardRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateSecretCardRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *UpdateSecretCardRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *UpdateSecretCardRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UpdateSecretCardRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type DeleteSecretCardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteSecretCardRequest) Reset() {
	*x = DeleteSecretCardRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_secretcard_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteSecretCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSecretCardRequest) ProtoMessage() {}

func (x *DeleteSecretCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_secretcard_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSecretCardRequest.ProtoReflect.Descriptor instead.
func (*DeleteSecretCardRequest) Descriptor() ([]byte, []int) {
	return file_secretcard_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteSecretCardRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListSecretCardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *ListSecretCardRequest) Reset() {
	*x = ListSecretCardRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_secretcard_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListSecretCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSecretCardRequest) ProtoMessage() {}

func (x *ListSecretCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_secretcard_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSecretCardRequest.ProtoReflect.Descriptor instead.
func (*ListSecretCardRequest) Descriptor() ([]byte, []int) {
	return file_secretcard_proto_rawDescGZIP(), []int{8}
}

func (x *ListSecretCardRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListSecretCardResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cards []*SecretCard `protobuf:"bytes,1,rep,name=cards,proto3" json:"cards,omitempty"`
}

func (x *ListSecretCardResponse) Reset() {
	*x = ListSecretCardResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_secretcard_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListSecretCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSecretCardResponse) ProtoMessage() {}

func (x *ListSecretCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_secretcard_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSecretCardResponse.ProtoReflect.Descriptor instead.
func (*ListSecretCardResponse) Descriptor() ([]byte, []int) {
	return file_secretcard_proto_rawDescGZIP(), []int{9}
}

func (x *ListSecretCardResponse) GetCards() []*SecretCard {
	if x != nil {
		return x.Cards
	}
	return nil
}

type ListMetaSecretCardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CardId string `protobuf:"bytes,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
}

func (x *ListMetaSecretCardRequest) Reset() {
	*x = ListMetaSecretCardRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_secretcard_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListMetaSecretCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMetaSecretCardRequest) ProtoMessage() {}

func (x *ListMetaSecretCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_secretcard_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMetaSecretCardRequest.ProtoReflect.Descriptor instead.
func (*ListMetaSecretCardRequest) Descriptor() ([]byte, []int) {
	return file_secretcard_proto_rawDescGZIP(), []int{10}
}

func (x *ListMetaSecretCardRequest) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

type ListMetaSecretCardResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cards []*MetaSecretCard `protobuf:"bytes,1,rep,name=cards,proto3" json:"cards,omitempty"`
}

func (x *ListMetaSecretCardResponse) Reset() {
	*x = ListMetaSecretCardResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_secretcard_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListMetaSecretCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMetaSecretCardResponse) ProtoMessage() {}

func (x *ListMetaSecretCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_secretcard_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMetaSecretCardResponse.ProtoReflect.Descriptor instead.
func (*ListMetaSecretCardResponse) Descriptor() ([]byte, []int) {
	return file_secretcard_proto_rawDescGZIP(), []int{11}
}

func (x *ListMetaSecretCardResponse) GetCards() []*MetaSecretCard {
	if x != nil {
		return x.Cards
	}
	return nil
}

type ReadMetaSecretCardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ReadMetaSecretCardRequest) Reset() {
	*x = ReadMetaSecretCardRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_secretcard_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadMetaSecretCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadMetaSecretCardRequest) ProtoMessage() {}

func (x *ReadMetaSecretCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_secretcard_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadMetaSecretCardRequest.ProtoReflect.Descriptor instead.
func (*ReadMetaSecretCardRequest) Descriptor() ([]byte, []int) {
	return file_secretcard_proto_rawDescGZIP(), []int{12}
}

func (x *ReadMetaSecretCardRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteMetaSecretCardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteMetaSecretCardRequest) Reset() {
	*x = DeleteMetaSecretCardRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_secretcard_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteMetaSecretCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMetaSecretCardRequest) ProtoMessage() {}

func (x *DeleteMetaSecretCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_secretcard_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMetaSecretCardRequest.ProtoReflect.Descriptor instead.
func (*DeleteMetaSecretCardRequest) Descriptor() ([]byte, []int) {
	return file_secretcard_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteMetaSecretCardRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CreateFileSecretCardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CardId string `protobuf:"bytes,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	File   []byte `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
}

func (x *CreateFileSecretCardRequest) Reset() {
	*x = CreateFileSecretCardRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_secretcard_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateFileSecretCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFileSecretCardRequest) ProtoMessage() {}

func (x *CreateFileSecretCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_secretcard_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFileSecretCardRequest.ProtoReflect.Descriptor instead.
func (*CreateFileSecretCardRequest) Descriptor() ([]byte, []int) {
	return file_secretcard_proto_rawDescGZIP(), []int{14}
}

func (x *CreateFileSecretCardRequest) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

func (x *CreateFileSecretCardRequest) GetFile() []byte {
	if x != nil {
		return x.File
	}
	return nil
}

type ReadFileSecretCardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ReadFileSecretCardRequest) Reset() {
	*x = ReadFileSecretCardRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_secretcard_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadFileSecretCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileSecretCardRequest) ProtoMessage() {}

func (x *ReadFileSecretCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_secretcard_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileSecretCardRequest.ProtoReflect.Descriptor instead.
func (*ReadFileSecretCardRequest) Descriptor() ([]byte, []int) {
	return file_secretcard_proto_rawDescGZIP(), []int{15}
}

func (x *ReadFileSecretCardRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateFileSecretCardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CardId string `protobuf:"bytes,2,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	File   []byte `protobuf:"bytes,3,opt,name=file,proto3" json:"file,omitempty"`
}

func (x *UpdateFileSecretCardRequest) Reset() {
	*x = UpdateFileSecretCardRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_secretcard_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateFileSecretCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFileSecretCardRequest) ProtoMessage() {}

func (x *UpdateFileSecretCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_secretcard_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFileSecretCardRequest.ProtoReflect.Descriptor instead.
func (*UpdateFileSecretCardRequest) Descriptor() ([]byte, []int) {
	return file_secretcard_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateFileSecretCardRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateFileSecretCardRequest) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

func (x *UpdateFileSecretCardRequest) GetFile() []byte {
	if x != nil {
		return x.File
	}
	return nil
}

type DeleteFileSecretCardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteFileSecretCardRequest) Reset() {
	*x = DeleteFileSecretCardRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_secretcard_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteFileSecretCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileSecretCardRequest) ProtoMessage() {}

func (x *DeleteFileSecretCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_secretcard_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileSecretCardRequest.ProtoReflect.Descriptor instead.
func (*DeleteFileSecretCardRequest) Descriptor() ([]byte, []int) {
	return file_secretcard_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteFileSecretCardRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListFileSecretCardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CardId string `protobuf:"bytes,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
}

func (x *ListFileSecretCardRequest) Reset() {
	*x = ListFileSecretCardRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_secretcard_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListFileSecretCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFileSecretCardRequest) ProtoMessage() {}

func (x *ListFileSecretCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_secretcard_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFileSecretCardRequest.ProtoReflect.Descriptor instead.
func (*ListFileSecretCardRequest) Descriptor() ([]byte, []int) {
	return file_secretcard_proto_rawDescGZIP(), []int{18}
}

func (x *ListFileSecretCardRequest) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

type ListFileSecretCardResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Files []*FileSecretCard `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
}

func (x *ListFileSecretCardResponse) Reset() {
	*x = ListFileSecretCardResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_secretcard_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListFileSecretCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFileSecretCardResponse) ProtoMessage() {}

func (x *ListFileSecretCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_secretcard_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFileSecretCardResponse.ProtoReflect.Descriptor instead.
func (*ListFileSecretCardResponse) Descriptor() ([]byte, []int) {
	return file_secretcard_proto_rawDescGZIP(), []int{19}
}

func (x *ListFileSecretCardResponse) GetFiles() []*FileSecretCard {
	if x != nil {
		return x.Files
	}
	return nil
}

var File_secretcard_proto protoreflect.FileDescriptor

var file_secretcard_proto_rawDesc = []byte{
	0x0a, 0x10, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x63, 0x61, 0x72, 0x64, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x02, 0x76, 0x31, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xde, 0x01, 0x0a, 0x0a, 0x53, 0x65, 0x63, 0x72,
	0x65, 0x74, 0x43, 0x61, 0x72, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x70,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x3b, 0x0a, 0x0b, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x4d, 0x0a, 0x0e, 0x46, 0x69, 0x6c, 0x65,
	0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x43, 0x61, 0x72, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x61,
	0x72, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x61, 0x72,
	0x64, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x22, 0x61, 0x0a, 0x0e, 0x4d, 0x65, 0x74, 0x61, 0x53,
	0x65, 0x63, 0x72, 0x65, 0x74, 0x43, 0x61, 0x72, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x61, 0x72,
	0x64, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x61, 0x72, 0x64,
	0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x22, 0x9e, 0x01, 0x0a, 0x17, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x65,
	0x63, 0x72, 0x65, 0x74, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x75, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x14,
	0x0a, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c,
	0x6f, 0x67, 0x69, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x65, 0x78, 0x74, 0x22, 0x27, 0x0a, 0x15, 0x52, 0x65, 0x61, 0x64, 0x53, 0x65, 0x63, 0x72,
	0x65, 0x74, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0xae, 0x01,
	0x0a, 0x17, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x43, 0x61,
	0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x6f, 0x67, 0x69,
	0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x1a,
	0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65,
	0x78, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x22, 0x29,
	0x0a, 0x17, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x43, 0x61,
	0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x30, 0x0a, 0x15, 0x4c, 0x69, 0x73,
	0x74, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x3e, 0x0a, 0x16, 0x4c,
	0x69, 0x73, 0x74, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x05, 0x63, 0x61, 0x72, 0x64, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74,
	0x43, 0x61, 0x72, 0x64, 0x52, 0x05, 0x63, 0x61, 0x72, 0x64, 0x73, 0x22, 0x34, 0x0a, 0x19, 0x4c,
	0x69, 0x73, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x43, 0x61, 0x72,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x61, 0x72, 0x64,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x61, 0x72, 0x64, 0x49,
	0x64, 0x22, 0x46, 0x0a, 0x1a, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x53, 0x65, 0x63,
	0x72, 0x65, 0x74, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x28, 0x0a, 0x05, 0x63, 0x61, 0x72, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12,
	0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x43, 0x61,
	0x72, 0x64, 0x52, 0x05, 0x63, 0x61, 0x72, 0x64, 0x73, 0x22, 0x2b, 0x0a, 0x19, 0x52, 0x65, 0x61,
	0x64, 0x4d, 0x65, 0x74, 0x61, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x43, 0x61, 0x72, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x2d, 0x0a, 0x1b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x4d, 0x65, 0x74, 0x61, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x4a, 0x0a, 0x1b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46,
	0x69, 0x6c, 0x65, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x61, 0x72, 0x64, 0x49, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x66, 0x69, 0x6c,
	0x65, 0x22, 0x2b, 0x0a, 0x19, 0x52, 0x65, 0x61, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x65, 0x63,
	0x72, 0x65, 0x74, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x5a,
	0x0a, 0x1b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x65, 0x63, 0x72,
	0x65, 0x74, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17, 0x0a,
	0x07, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x63, 0x61, 0x72, 0x64, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x22, 0x2d, 0x0a, 0x1b, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x43, 0x61,
	0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x34, 0x0a, 0x19, 0x4c, 0x69, 0x73,
	0x74, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x43, 0x61, 0x72, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x61, 0x72, 0x64, 0x49, 0x64, 0x22,
	0x46, 0x0a, 0x1a, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x65, 0x63, 0x72, 0x65,
	0x74, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a,
	0x05, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x76,
	0x31, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x43, 0x61, 0x72, 0x64,
	0x52, 0x05, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x32, 0xd7, 0x02, 0x0a, 0x11, 0x53, 0x65, 0x63, 0x72,
	0x65, 0x74, 0x43, 0x61, 0x72, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3f, 0x0a,
	0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x43, 0x61, 0x72,
	0x64, 0x12, 0x1b, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x65, 0x63,
	0x72, 0x65, 0x74, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e,
	0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x43, 0x61, 0x72, 0x64, 0x12, 0x3b,
	0x0a, 0x0e, 0x52, 0x65, 0x61, 0x64, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x43, 0x61, 0x72, 0x64,
	0x12, 0x19, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74,
	0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x76, 0x31,
	0x2e, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x43, 0x61, 0x72, 0x64, 0x12, 0x3f, 0x0a, 0x10, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x43, 0x61, 0x72, 0x64, 0x12,
	0x1b, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x65, 0x63, 0x72, 0x65,
	0x74, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x76,
	0x31, 0x2e, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x43, 0x61, 0x72, 0x64, 0x12, 0x3a, 0x0a, 0x10,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x43, 0x61, 0x72, 0x64,
	0x12, 0x1b, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x65, 0x63, 0x72,
	0x65, 0x74, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x09, 0x2e,
	0x76, 0x31, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x47, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74,
	0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x43, 0x61, 0x72, 0x64, 0x12, 0x19, 0x2e, 0x76, 0x31, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x53,
	0x65, 0x63, 0x72, 0x65, 0x74, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x32, 0xf9, 0x02, 0x0a, 0x15, 0x4d, 0x65, 0x74, 0x61, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74,
	0x43, 0x61, 0x72, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3e, 0x0a, 0x14, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x43,
	0x61, 0x72, 0x64, 0x12, 0x12, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x53, 0x65, 0x63,
	0x72, 0x65, 0x74, 0x43, 0x61, 0x72, 0x64, 0x1a, 0x12, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x65, 0x74,
	0x61, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x43, 0x61, 0x72, 0x64, 0x12, 0x47, 0x0a, 0x12, 0x52,
	0x65, 0x61, 0x64, 0x4d, 0x65, 0x74, 0x61, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x43, 0x61, 0x72,
	0x64, 0x12, 0x1d, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x4d, 0x65, 0x74, 0x61, 0x53,
	0x65, 0x63, 0x72, 0x65, 0x74, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x12, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74,
	0x43, 0x61, 0x72, 0x64, 0x12, 0x3e, 0x0a, 0x14, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x65,
	0x74, 0x61, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x43, 0x61, 0x72, 0x64, 0x12, 0x12, 0x2e, 0x76,
	0x31, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x43, 0x61, 0x72, 0x64,
	0x1a, 0x12, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74,
	0x43, 0x61, 0x72, 0x64, 0x12, 0x42, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x65,
	0x74, 0x61, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x43, 0x61, 0x72, 0x64, 0x12, 0x1f, 0x2e, 0x76,
	0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x53, 0x65, 0x63, 0x72,
	0x65, 0x74, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x09, 0x2e,
	0x76, 0x31, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x53, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74,
	0x4d, 0x65, 0x74, 0x61, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x43, 0x61, 0x72, 0x64, 0x12, 0x1d,
	0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x53, 0x65, 0x63, 0x72,
	0x65, 0x74, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e,
	0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x53, 0x65, 0x63, 0x72, 0x65,
	0x74, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x93, 0x03,
	0x0a, 0x15, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x43, 0x61, 0x72, 0x64,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4b, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x43, 0x61, 0x72, 0x64, 0x12,
	0x1f, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x53,
	0x65, 0x63, 0x72, 0x65, 0x74, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x12, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74,
	0x43, 0x61, 0x72, 0x64, 0x12, 0x47, 0x0a, 0x12, 0x52, 0x65, 0x61, 0x64, 0x46, 0x69, 0x6c, 0x65,
	0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x43, 0x61, 0x72, 0x64, 0x12, 0x1d, 0x2e, 0x76, 0x31, 0x2e,
	0x52, 0x65, 0x61, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x43, 0x61,
	0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x76, 0x31, 0x2e, 0x46,
	0x69, 0x6c, 0x65, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x43, 0x61, 0x72, 0x64, 0x12, 0x4b, 0x0a,
	0x14, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x65, 0x63, 0x72, 0x65,
	0x74, 0x43, 0x61, 0x72, 0x64, 0x12, 0x1f, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x43, 0x61, 0x72, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x69, 0x6c, 0x65,
	0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x43, 0x61, 0x72, 0x64, 0x12, 0x42, 0x0a, 0x14, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x43, 0x61,
	0x72, 0x64, 0x12, 0x1f, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x69,
	0x6c, 0x65, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x09, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x53,
	0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74,
	0x43, 0x61, 0x72, 0x64, 0x12, 0x1d, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x69,
	0x6c, 0x65, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x69, 0x6c,
	0x65, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x0a, 0x5a, 0x08, 0x76, 0x31, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_secretcard_proto_rawDescOnce sync.Once
	file_secretcard_proto_rawDescData = file_secretcard_proto_rawDesc
)

func file_secretcard_proto_rawDescGZIP() []byte {
	file_secretcard_proto_rawDescOnce.Do(func() {
		file_secretcard_proto_rawDescData = protoimpl.X.CompressGZIP(file_secretcard_proto_rawDescData)
	})
	return file_secretcard_proto_rawDescData
}

var file_secretcard_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_secretcard_proto_goTypes = []interface{}{
	(*SecretCard)(nil),                  // 0: v1.SecretCard
	(*FileSecretCard)(nil),              // 1: v1.FileSecretCard
	(*MetaSecretCard)(nil),              // 2: v1.MetaSecretCard
	(*Empty)(nil),                       // 3: v1.Empty
	(*CreateSecretCardRequest)(nil),     // 4: v1.CreateSecretCardRequest
	(*ReadSecretCardRequest)(nil),       // 5: v1.ReadSecretCardRequest
	(*UpdateSecretCardRequest)(nil),     // 6: v1.UpdateSecretCardRequest
	(*DeleteSecretCardRequest)(nil),     // 7: v1.DeleteSecretCardRequest
	(*ListSecretCardRequest)(nil),       // 8: v1.ListSecretCardRequest
	(*ListSecretCardResponse)(nil),      // 9: v1.ListSecretCardResponse
	(*ListMetaSecretCardRequest)(nil),   // 10: v1.ListMetaSecretCardRequest
	(*ListMetaSecretCardResponse)(nil),  // 11: v1.ListMetaSecretCardResponse
	(*ReadMetaSecretCardRequest)(nil),   // 12: v1.ReadMetaSecretCardRequest
	(*DeleteMetaSecretCardRequest)(nil), // 13: v1.DeleteMetaSecretCardRequest
	(*CreateFileSecretCardRequest)(nil), // 14: v1.CreateFileSecretCardRequest
	(*ReadFileSecretCardRequest)(nil),   // 15: v1.ReadFileSecretCardRequest
	(*UpdateFileSecretCardRequest)(nil), // 16: v1.UpdateFileSecretCardRequest
	(*DeleteFileSecretCardRequest)(nil), // 17: v1.DeleteFileSecretCardRequest
	(*ListFileSecretCardRequest)(nil),   // 18: v1.ListFileSecretCardRequest
	(*ListFileSecretCardResponse)(nil),  // 19: v1.ListFileSecretCardResponse
	(*timestamppb.Timestamp)(nil),       // 20: google.protobuf.Timestamp
}
var file_secretcard_proto_depIdxs = []int32{
	20, // 0: v1.SecretCard.update_time:type_name -> google.protobuf.Timestamp
	0,  // 1: v1.ListSecretCardResponse.cards:type_name -> v1.SecretCard
	2,  // 2: v1.ListMetaSecretCardResponse.cards:type_name -> v1.MetaSecretCard
	1,  // 3: v1.ListFileSecretCardResponse.files:type_name -> v1.FileSecretCard
	4,  // 4: v1.SecretCardService.CreateSecretCard:input_type -> v1.CreateSecretCardRequest
	5,  // 5: v1.SecretCardService.ReadSecretCard:input_type -> v1.ReadSecretCardRequest
	6,  // 6: v1.SecretCardService.UpdateSecretCard:input_type -> v1.UpdateSecretCardRequest
	7,  // 7: v1.SecretCardService.DeleteSecretCard:input_type -> v1.DeleteSecretCardRequest
	8,  // 8: v1.SecretCardService.ListSecretCard:input_type -> v1.ListSecretCardRequest
	2,  // 9: v1.MetaSecretCardService.CreateMetaSecretCard:input_type -> v1.MetaSecretCard
	12, // 10: v1.MetaSecretCardService.ReadMetaSecretCard:input_type -> v1.ReadMetaSecretCardRequest
	2,  // 11: v1.MetaSecretCardService.UpdateMetaSecretCard:input_type -> v1.MetaSecretCard
	13, // 12: v1.MetaSecretCardService.DeleteMetaSecretCard:input_type -> v1.DeleteMetaSecretCardRequest
	10, // 13: v1.MetaSecretCardService.ListMetaSecretCard:input_type -> v1.ListMetaSecretCardRequest
	14, // 14: v1.FileSecretCardService.CreateFileSecretCard:input_type -> v1.CreateFileSecretCardRequest
	15, // 15: v1.FileSecretCardService.ReadFileSecretCard:input_type -> v1.ReadFileSecretCardRequest
	16, // 16: v1.FileSecretCardService.UpdateFileSecretCard:input_type -> v1.UpdateFileSecretCardRequest
	17, // 17: v1.FileSecretCardService.DeleteFileSecretCard:input_type -> v1.DeleteFileSecretCardRequest
	18, // 18: v1.FileSecretCardService.ListFileSecretCard:input_type -> v1.ListFileSecretCardRequest
	0,  // 19: v1.SecretCardService.CreateSecretCard:output_type -> v1.SecretCard
	0,  // 20: v1.SecretCardService.ReadSecretCard:output_type -> v1.SecretCard
	0,  // 21: v1.SecretCardService.UpdateSecretCard:output_type -> v1.SecretCard
	3,  // 22: v1.SecretCardService.DeleteSecretCard:output_type -> v1.Empty
	9,  // 23: v1.SecretCardService.ListSecretCard:output_type -> v1.ListSecretCardResponse
	2,  // 24: v1.MetaSecretCardService.CreateMetaSecretCard:output_type -> v1.MetaSecretCard
	2,  // 25: v1.MetaSecretCardService.ReadMetaSecretCard:output_type -> v1.MetaSecretCard
	2,  // 26: v1.MetaSecretCardService.UpdateMetaSecretCard:output_type -> v1.MetaSecretCard
	3,  // 27: v1.MetaSecretCardService.DeleteMetaSecretCard:output_type -> v1.Empty
	11, // 28: v1.MetaSecretCardService.ListMetaSecretCard:output_type -> v1.ListMetaSecretCardResponse
	1,  // 29: v1.FileSecretCardService.CreateFileSecretCard:output_type -> v1.FileSecretCard
	1,  // 30: v1.FileSecretCardService.ReadFileSecretCard:output_type -> v1.FileSecretCard
	1,  // 31: v1.FileSecretCardService.UpdateFileSecretCard:output_type -> v1.FileSecretCard
	3,  // 32: v1.FileSecretCardService.DeleteFileSecretCard:output_type -> v1.Empty
	19, // 33: v1.FileSecretCardService.ListFileSecretCard:output_type -> v1.ListFileSecretCardResponse
	19, // [19:34] is the sub-list for method output_type
	4,  // [4:19] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_secretcard_proto_init() }
func file_secretcard_proto_init() {
	if File_secretcard_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_secretcard_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SecretCard); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_secretcard_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileSecretCard); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_secretcard_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetaSecretCard); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_secretcard_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_secretcard_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSecretCardRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_secretcard_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadSecretCardRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_secretcard_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateSecretCardRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_secretcard_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteSecretCardRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_secretcard_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListSecretCardRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_secretcard_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListSecretCardResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_secretcard_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListMetaSecretCardRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_secretcard_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListMetaSecretCardResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_secretcard_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadMetaSecretCardRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_secretcard_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteMetaSecretCardRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_secretcard_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateFileSecretCardRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_secretcard_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadFileSecretCardRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_secretcard_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateFileSecretCardRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_secretcard_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteFileSecretCardRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_secretcard_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListFileSecretCardRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_secretcard_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListFileSecretCardResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_secretcard_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_secretcard_proto_goTypes,
		DependencyIndexes: file_secretcard_proto_depIdxs,
		MessageInfos:      file_secretcard_proto_msgTypes,
	}.Build()
	File_secretcard_proto = out.File
	file_secretcard_proto_rawDesc = nil
	file_secretcard_proto_goTypes = nil
	file_secretcard_proto_depIdxs = nil
}
